'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("25")>  _
        Public Property Codepoints() As Decimal
            Get
                Return CType(Me("Codepoints"),Decimal)
            End Get
            Set
                Me("Codepoints") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtGray() As Boolean
            Get
                Return CType(Me("BoughtGray"),Boolean)
            End Get
            Set
                Me("BoughtGray") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtTitlebar() As Boolean
            Get
                Return CType(Me("BoughtTitlebar"),Boolean)
            End Get
            Set
                Me("BoughtTitlebar") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtBorders() As Boolean
            Get
                Return CType(Me("BoughtBorders"),Boolean)
            End Get
            Set
                Me("BoughtBorders") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtDesktopPanel() As Boolean
            Get
                Return CType(Me("BoughtDesktopPanel"),Boolean)
            End Get
            Set
                Me("BoughtDesktopPanel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtDraggableWindows() As Boolean
            Get
                Return CType(Me("BoughtDraggableWindows"),Boolean)
            End Get
            Set
                Me("BoughtDraggableWindows") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property TerminalWindowed() As Boolean
            Get
                Return CType(Me("TerminalWindowed"),Boolean)
            End Get
            Set
                Me("TerminalWindowed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtWindowedTerminal() As Boolean
            Get
                Return CType(Me("BoughtWindowedTerminal"),Boolean)
            End Get
            Set
                Me("BoughtWindowedTerminal") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtGrayShades() As Boolean
            Get
                Return CType(Me("BoughtGrayShades"),Boolean)
            End Get
            Set
                Me("BoughtGrayShades") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtTitlebarText() As Boolean
            Get
                Return CType(Me("BoughtTitlebarText"),Boolean)
            End Get
            Set
                Me("BoughtTitlebarText") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtCloseButton() As Boolean
            Get
                Return CType(Me("BoughtCloseButton"),Boolean)
            End Get
            Set
                Me("BoughtCloseButton") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtGraySet() As Boolean
            Get
                Return CType(Me("BoughtGraySet"),Boolean)
            End Get
            Set
                Me("BoughtGraySet") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtALShiftorium() As Boolean
            Get
                Return CType(Me("BoughtALShiftorium"),Boolean)
            End Get
            Set
                Me("BoughtALShiftorium") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtALShutdown() As Boolean
            Get
                Return CType(Me("BoughtALShutdown"),Boolean)
            End Get
            Set
                Me("BoughtALShutdown") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtALCPClicker() As Boolean
            Get
                Return CType(Me("BoughtALCPClicker"),Boolean)
            End Get
            Set
                Me("BoughtALCPClicker") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtALClock() As Boolean
            Get
                Return CType(Me("BoughtALClock"),Boolean)
            End Get
            Set
                Me("BoughtALClock") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtClock() As Boolean
            Get
                Return CType(Me("BoughtClock"),Boolean)
            End Get
            Set
                Me("BoughtClock") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtHoursSinceMidnight() As Boolean
            Get
                Return CType(Me("BoughtHoursSinceMidnight"),Boolean)
            End Get
            Set
                Me("BoughtHoursSinceMidnight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtMinutesSinceMidnight() As Boolean
            Get
                Return CType(Me("BoughtMinutesSinceMidnight"),Boolean)
            End Get
            Set
                Me("BoughtMinutesSinceMidnight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtPMandAM() As Boolean
            Get
                Return CType(Me("BoughtPMandAM"),Boolean)
            End Get
            Set
                Me("BoughtPMandAM") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtMinuteAccuracyTime() As Boolean
            Get
                Return CType(Me("BoughtMinuteAccuracyTime"),Boolean)
            End Get
            Set
                Me("BoughtMinuteAccuracyTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtSplitSecondTime() As Boolean
            Get
                Return CType(Me("BoughtSplitSecondTime"),Boolean)
            End Get
            Set
                Me("BoughtSplitSecondTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtDesktopPanelClock() As Boolean
            Get
                Return CType(Me("BoughtDesktopPanelClock"),Boolean)
            End Get
            Set
                Me("BoughtDesktopPanelClock") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property CPClickerUpgradeAmount() As Decimal
            Get
                Return CType(Me("CPClickerUpgradeAmount"),Decimal)
            End Get
            Set
                Me("CPClickerUpgradeAmount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CPperClick() As Decimal
            Get
                Return CType(Me("CPperClick"),Decimal)
            End Get
            Set
                Me("CPperClick") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property CPClickerUpgradeAmount2() As Decimal
            Get
                Return CType(Me("CPClickerUpgradeAmount2"),Decimal)
            End Get
            Set
                Me("CPClickerUpgradeAmount2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CPperClick2() As Decimal
            Get
                Return CType(Me("CPperClick2"),Decimal)
            End Get
            Set
                Me("CPperClick2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DoIntro() As Boolean
            Get
                Return CType(Me("DoIntro"),Boolean)
            End Get
            Set
                Me("DoIntro") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtShifter() As Boolean
            Get
                Return CType(Me("BoughtShifter"),Boolean)
            End Get
            Set
                Me("BoughtShifter") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtALShifter() As Boolean
            Get
                Return CType(Me("BoughtALShifter"),Boolean)
            End Get
            Set
                Me("BoughtALShifter") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
        Public Property closecolor() As Global.System.Drawing.Color
            Get
                Return CType(Me("closecolor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("closecolor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtRed() As Boolean
            Get
                Return CType(Me("BoughtRed"),Boolean)
            End Get
            Set
                Me("BoughtRed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtOrange() As Boolean
            Get
                Return CType(Me("BoughtOrange"),Boolean)
            End Get
            Set
                Me("BoughtOrange") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtYellow() As Boolean
            Get
                Return CType(Me("BoughtYellow"),Boolean)
            End Get
            Set
                Me("BoughtYellow") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtGreen() As Boolean
            Get
                Return CType(Me("BoughtGreen"),Boolean)
            End Get
            Set
                Me("BoughtGreen") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtBlue() As Boolean
            Get
                Return CType(Me("BoughtBlue"),Boolean)
            End Get
            Set
                Me("BoughtBlue") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtPurple() As Boolean
            Get
                Return CType(Me("BoughtPurple"),Boolean)
            End Get
            Set
                Me("BoughtPurple") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtPink() As Boolean
            Get
                Return CType(Me("BoughtPink"),Boolean)
            End Get
            Set
                Me("BoughtPink") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtBrown() As Boolean
            Get
                Return CType(Me("BoughtBrown"),Boolean)
            End Get
            Set
                Me("BoughtBrown") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Gray")>  _
        Public Property titlebarcolor() As Global.System.Drawing.Color
            Get
                Return CType(Me("titlebarcolor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("titlebarcolor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Gray")>  _
        Public Property bordercolor() As Global.System.Drawing.Color
            Get
                Return CType(Me("bordercolor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("bordercolor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
        Public Property titlebartextcolor() As Global.System.Drawing.Color
            Get
                Return CType(Me("titlebartextcolor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("titlebartextcolor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
        Public Property desktopcolor() As Global.System.Drawing.Color
            Get
                Return CType(Me("desktopcolor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("desktopcolor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtRedShades() As Boolean
            Get
                Return CType(Me("BoughtRedShades"),Boolean)
            End Get
            Set
                Me("BoughtRedShades") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Gray")>  _
        Public Property desktoppanelcolor() As Global.System.Drawing.Color
            Get
                Return CType(Me("desktoppanelcolor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("desktoppanelcolor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Gray")>  _
        Public Property applaunchercolor() As Global.System.Drawing.Color
            Get
                Return CType(Me("applaunchercolor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("applaunchercolor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Gray")>  _
        Public Property menucolor() As Global.System.Drawing.Color
            Get
                Return CType(Me("menucolor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("menucolor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtOrangeShades() As Boolean
            Get
                Return CType(Me("BoughtOrangeShades"),Boolean)
            End Get
            Set
                Me("BoughtOrangeShades") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtYellowShades() As Boolean
            Get
                Return CType(Me("BoughtYellowShades"),Boolean)
            End Get
            Set
                Me("BoughtYellowShades") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtGreenShades() As Boolean
            Get
                Return CType(Me("BoughtGreenShades"),Boolean)
            End Get
            Set
                Me("BoughtGreenShades") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtBlueShades() As Boolean
            Get
                Return CType(Me("BoughtBlueShades"),Boolean)
            End Get
            Set
                Me("BoughtBlueShades") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtPurpleShades() As Boolean
            Get
                Return CType(Me("BoughtPurpleShades"),Boolean)
            End Get
            Set
                Me("BoughtPurpleShades") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtPinkShades() As Boolean
            Get
                Return CType(Me("BoughtPinkShades"),Boolean)
            End Get
            Set
                Me("BoughtPinkShades") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtBrownShades() As Boolean
            Get
                Return CType(Me("BoughtBrownShades"),Boolean)
            End Get
            Set
                Me("BoughtBrownShades") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Setting() As Boolean
            Get
                Return CType(Me("Setting"),Boolean)
            End Get
            Set
                Me("Setting") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
        Public Property panelclocktextcolor() As Global.System.Drawing.Color
            Get
                Return CType(Me("panelclocktextcolor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("panelclocktextcolor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
        Public Property menutextcolor() As Global.System.Drawing.Color
            Get
                Return CType(Me("menutextcolor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("menutextcolor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Gray")>  _
        Public Property panelclockcolor() As Global.System.Drawing.Color
            Get
                Return CType(Me("panelclockcolor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("panelclockcolor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("11")>  _
        Public Property ttextsize() As Decimal
            Get
                Return CType(Me("ttextsize"),Decimal)
            End Get
            Set
                Me("ttextsize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 11.5pt")>  _
        Public Property ttextfont() As Global.System.Drawing.Font
            Get
                Return CType(Me("ttextfont"),Global.System.Drawing.Font)
            End Get
            Set
                Me("ttextfont") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Bold")>  _
        Public Property ttextstyle() As String
            Get
                Return CType(Me("ttextstyle"),String)
            End Get
            Set
                Me("ttextstyle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
        Public Property clocktextcolor() As Global.System.Drawing.Color
            Get
                Return CType(Me("clocktextcolor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("clocktextcolor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif")>  _
        Public Property ttextfontname() As String
            Get
                Return CType(Me("ttextfontname"),String)
            End Get
            Set
                Me("ttextfontname") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Top")>  _
        Public Property desktoppanellocation() As String
            Get
                Return CType(Me("desktoppanellocation"),String)
            End Get
            Set
                Me("desktoppanellocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtRedSet() As Boolean
            Get
                Return CType(Me("BoughtRedSet"),Boolean)
            End Get
            Set
                Me("BoughtRedSet") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtOrangeSet() As Boolean
            Get
                Return CType(Me("BoughtOrangeSet"),Boolean)
            End Get
            Set
                Me("BoughtOrangeSet") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtYellowSet() As Boolean
            Get
                Return CType(Me("BoughtYellowSet"),Boolean)
            End Get
            Set
                Me("BoughtYellowSet") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtGreenSet() As Boolean
            Get
                Return CType(Me("BoughtGreenSet"),Boolean)
            End Get
            Set
                Me("BoughtGreenSet") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtBlueSet() As Boolean
            Get
                Return CType(Me("BoughtBlueSet"),Boolean)
            End Get
            Set
                Me("BoughtBlueSet") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtPurpleSet() As Boolean
            Get
                Return CType(Me("BoughtPurpleSet"),Boolean)
            End Get
            Set
                Me("BoughtPurpleSet") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtPinkSet() As Boolean
            Get
                Return CType(Me("BoughtPinkSet"),Boolean)
            End Get
            Set
                Me("BoughtPinkSet") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtBrownSet() As Boolean
            Get
                Return CType(Me("BoughtBrownSet"),Boolean)
            End Get
            Set
                Me("BoughtBrownSet") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
        Public Property launchertextcolor() As Global.System.Drawing.Color
            Get
                Return CType(Me("launchertextcolor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("launchertextcolor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Applications")>  _
        Public Property launcherlabel() As String
            Get
                Return CType(Me("launcherlabel"),String)
            End Get
            Set
                Me("launcherlabel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
        Public Property lmenutextcolor() As Global.System.Drawing.Color
            Get
                Return CType(Me("lmenutextcolor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("lmenutextcolor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtTextpad() As Boolean
            Get
                Return CType(Me("BoughtTextpad"),Boolean)
            End Get
            Set
                Me("BoughtTextpad") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtALTextpad() As Boolean
            Get
                Return CType(Me("BoughtALTextpad"),Boolean)
            End Get
            Set
                Me("BoughtALTextpad") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property VersionPirated() As Boolean
            Get
                Return CType(Me("VersionPirated"),Boolean)
            End Get
            Set
                Me("VersionPirated") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtFileSkimmer() As Boolean
            Get
                Return CType(Me("BoughtFileSkimmer"),Boolean)
            End Get
            Set
                Me("BoughtFileSkimmer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BoughtALFileSkimmer() As Boolean
            Get
                Return CType(Me("BoughtALFileSkimmer"),Boolean)
            End Get
            Set
                Me("BoughtALFileSkimmer") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.ShiftOS_Remade.My.MySettings
            Get
                Return Global.ShiftOS_Remade.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
